# Generated by Django 5.2.9 on 2025-12-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('trim', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('milage', models.IntegerField()),
                ('sale_pending', models.BooleanField()),
                ('sold', models.BooleanField()),
                ('days_on_lot', models.IntegerField()),
            ],
        ),
    ]
