# Generated by Django 5.2.9 on 2025-12-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.AddField(
            model_name='car',
            name='buyer',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price_listed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price_sold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='days_on_lot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='milage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='sale_pending',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='sold',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='trim',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
