# Generated by Django 5.2.9 on 2025-12-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_api', '0002_remove_car_price_car_buyer_car_price_listed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
